version: '3.8'

services:
  app:
    build:
      context: .
      target: node:18-alpine
    command: pnpm run dev
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/anvoria
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
